default_language_version:
  python: python3.12

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml

- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.1
  hooks:
  - id: pyupgrade
    args: ['--keep-percent-format', '--py310-plus']

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.9
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.15.0'
  hooks:
  - id: mypy
    alias: mypy_easy
    additional_dependencies:
    - types-attrs
    - types-chardet
    - types-frozendict
    - types-requests
    - types-python-dateutil
    - types-pytz
    - types-PyYAML
    exclude: ^(data|\w+/tests)/

  - id: mypy
    alias: mypy_strict
    args: ['--check-untyped-defs']
    additional_dependencies:
    - types-attrs
    - types-chardet
    - types-frozendict
    - types-requests
    - types-python-dateutil
    - types-pytz
    - types-PyYAML
    exclude: ^(\w+/tests)
